Repository janhq/cortex.so, pull requests merged in 2024-06, with the labels that each got.

#2 fix: update simple landing page
  docusaurus.config.ts
  src/pages/index.tsx
Labels: type: bug

#5 chore: update landing page
  package.json
  src/components/typeWriterWffect.tsx
  src/pages/index.tsx
  yarn.lock
Labels: type: chore

#6 feat(scalar): Upload OpenAPI JSON file for Jan Cortex to render on Sc…
  static/openapi/jan.json
Labels: type: documentation

#7 feat(scalar): Scalar implementation
  docusaurus.config.ts
  package.json
Labels: type: documentation

#18 docs: model operations
  docs/installation/linux.mdx
  docs/installation/mac.mdx
  docs/installation/windows.mdx
  docs/model-operations.mdx
  package.json
  sidebars.ts
Labels: type: bug

#29 docs: Embeddings Updates
  docs/embeddings.mdx
Labels: type: documentation

#33 docs: Make the header consistent and Update the cortex init page
  docs/cli/chat.md
  docs/cli/cortex.md
  docs/cli/embeddings.mdx
  docs/cli/init.md
  docs/cli/presets.mdx
  docs/cli/run.md
  docs/installation/linux.mdx
  docs/installation/mac.mdx
  docs/installation/windows.mdx
  docs/server.mdx
  docusaurus.config.ts
  src/components/OAICoverage/index.tsx
Labels: type: documentation

#34 feat: update daily fetch coverage
  .github/workflows/docs.yml
  docusaurus.config.ts
  src/components/OAICoverage/index.tsx
Labels: type: feature request

#35 fix: update CI event schedule
  .github/workflows/docs.yml
  docusaurus.config.ts
Labels: type: bug

#36 docs: Update the embeddings page
  docs/embeddings.mdx
Labels: type: documentation

#37 docs: Update the cli and architecture docs
  docs/architecture.md
  docs/cli/benchmark.mdx
  docs/cli/chat.md
  docs/cli/cortex.md
  docs/cli/embeddings.mdx
  docs/cli/init.md
  docs/cli/kill.md
  docs/cli/models/download.md
  docs/cli/models/get.md
  docs/cli/models/index.md
  docs/cli/models/list.md
  docs/cli/models/remove.md
  docs/cli/models/start.md
  docs/cli/models/stop.md
  docs/cli/models/update.md
  docs/cli/presets.mdx
  docs/cli/pull.md
  docs/cli/run.md
  docs/cli/serve.md
  sidebars.ts
Labels: type: documentation

#38 docs: Update the CLI and Endpoint pages to reflect the new changes
  docs/cli/benchmark.mdx
  docs/cli/chat.md
  docs/cli/cortex.md
  docs/cli/embeddings.mdx
  docs/cli/init.md
  docs/cli/kill.md
  docs/cli/models/download.md
  docs/cli/models/get.md
  docs/cli/models/index.md
  docs/cli/models/list.md
  docs/cli/models/remove.md
  docs/cli/models/start.md
  docs/cli/models/stop.md
  docs/cli/models/update.md
  docs/cli/presets.mdx
  docs/cli/ps.md
  docs/cli/pull.md
  docs/cli/run.md
  docs/cli/serve.md
  docs/cli/telemetry.mdx
  docs/embeddings.mdx
  sidebars.ts
  static/openapi/jan.json
Labels: type: documentation

#39 docs: Add crash report architecture and implementation
  docs/telemetry.mdx
  sidebars.ts
  static/img/docs/catch-crash.png
  static/img/docs/telemetry-architecture.png
  static/img/docs/telemetry1.png
  static/img/docs/telemetry2.png
Labels: type: documentation

#41 docs: Update the docs
  docs/architecture.md
  docs/chat-completions.mdx
  docs/cli/models/start.md
  docs/cli/run.md
  docs/command-line.md
  docs/cortex-llamacpp.md
  docs/embeddings.mdx
  docs/model-operations.mdx
  sidebars.ts
  static/img/docs/cortex-runtime.png
  static/img/docs/llama-cpp1.png
  static/img/docs/llama-cpp2.png
Labels: type: documentation

#43 docs: Added the onnx architecture page
  docs/cortex-llamacpp.md
  docs/cortex-onnx.mdx
  docs/quickstart.md
  sidebars.ts
  static/img/docs/onnx-1.png
  static/img/docs/onnx-2.png
  static/img/docs/onnx-3.png
  static/img/docs/onnx-4.png
Labels: type: documentation

#49 fix: quickstart
  docs/overview.md
  docs/quickstart.md
  docs/server.mdx
Labels: type: bug

#54 docs: update quickstart and cortex.tensorrtllm
  docs/cortex-llamacpp.md
  docs/cortex-onnx.mdx
  docs/cortex-tensorrt-llm.mdx
  docs/model-operations.mdx
  docs/quickstart.md
  sidebars.ts
Labels: type: documentation

#62 Update the Installation and embeddings pages
  docs/embeddings.mdx
  docs/installation/linux.mdx
  docs/installation/mac.mdx
  docs/installation/windows.mdx
Labels: type: feature request

#65 Update the Benchmark page
  docs/benchmark.mdx
  docs/embeddings.mdx
  sidebars.ts
Labels: type: feature request
