Repository janhq/cortex.so, pull requests merged in 2024-08, with the labels that each got.

#164 fix: update career link
  docusaurus.config.ts
Labels: type: bug

#169 chore: update engine logo
  static/img/logos/anthropic.svg
  static/img/logos/cohere.svg
  static/img/logos/cortex.svg
  static/img/logos/dot.svg
  static/img/logos/groq.svg
  static/img/logos/martian.svg
  static/img/logos/meta.svg
  static/img/logos/mistral.svg
  static/img/logos/openai.svg
  static/img/logos/openrouter.svg
  static/img/logos/send.svg
Labels: type: chore

#170 fix: downgrade scalar package
  docusaurus.config.ts
  package.json
  yarn.lock
Labels: type: bug

#174 chore: update nvdia logo
  static/img/logos/nvidia.svg
Labels: type: chore

#176 fix: responsive my model
  src/pages/models.tsx
Labels: type: bug

#177 feat: add how to integrate remote engine page
  docs/integrate-remote-engine.mdx
  sidebars.ts
Labels: type: feature request
