Repository janhq/cortex.so, pull requests merged in 2024-07, with the labels that each got.

#71 fix: algolia search no result
  docusaurus.config.ts
Labels: type: bug

#72 feat: Create hub.json for model info
  static/huggingface/hub.json
Labels: type: feature request

#75 docs: Models docs pages
  docs/benchmarking.mdx
  docs/curated-models.mdx
  docs/hub/hugging-face.mdx
  docs/hub/nvidia-ngc.mdx
  docs/model-operations.mdx
  docs/model-yaml.mdx
  docs/quickstart.md
  docs/requirements.mdx
  sidebars.ts
Labels: type: documentation

#77 feat: setup google tag analytic
  .env.example
  docusaurus.config.ts
  static/js/gtag.js
Labels: type: feature request

#86 fix: update minor ui landing
  src/containers/Homepage/About/index.tsx
  src/containers/Homepage/GettingStartedSection/index.tsx
  src/containers/Homepage/HeroSection/index.tsx
  src/containers/Homepage/OAIReplacement/index.tsx
  src/pages/models.tsx
  src/theme/Footer/index.tsx
  static/img/homepage/model-registry-dark.png
  static/img/homepage/model-registry.png
Labels: type: bug

#87 chore: Add mode‌l providers lo‌go
  static/img/logos/anthropic.svg
  static/img/logos/cohere.svg
  static/img/logos/martian.svg
  static/img/logos/mistral.svg
  static/img/logos/openai.svg
Labels: type: chore

#91 fix: added badge coming soon
  src/containers/Homepage/OAIReplacement/index.tsx
Labels: type: bug

#92 chore: copy fixes
  src/containers/Homepage/About/index.tsx
  src/containers/Homepage/GettingStartedSection/index.tsx
  src/containers/Homepage/OAIReplacement/index.tsx
Labels: type: chore

#93 docs: telemetry export page
  docs/telemetry-export.mdx
  docs/telemetry.mdx
  sidebars.ts
Labels: type: documentation

#94 chore: quickstart change llama to mistral
  docs/quickstart.md
Labels: type: chore, type: documentation

#96 fix: remove badge tensorrt from llama3
  src/containers/Homepage/HeroSection/index.tsx
  src/pages/models.tsx
Labels: type: bug

#97 fix: missing link url
  docusaurus.config.ts
  src/components/SocialNavbar/index.tsx
Labels: type: bug

#99 fix: update social card preview image
  static/img/cortex-social-card.png
Labels: type: bug

#100 fix: update social image preview
  static/img/cortex-social-card.png
Labels: type: bug

#101 fix: seo og description
  docusaurus.config.ts
  static/img/cortex-social-card.png
  static/img/social-card.jpg
Labels: type: bug

#106 docs: update telemetry export env name
  docs/telemetry-export.mdx
Labels: type: documentation

#108 fix: update label linux package
  src/containers/Homepage/Download/CardDownload.tsx
Labels: type: bug

#111 feat: update hardware section
  src/containers/Homepage/OAIReplacement/index.tsx
  static/img/homepage/cpus_npus.png
  static/img/homepage/phones.png
  static/img/homepage/robots.png
  static/img/homepage/server.png
Labels: type: enhancement, type: feature request

#119 chore: remove logo from hub.json
  static/huggingface/hub.json
Labels: type: chore

#118 feat: update style OAI coverage chart
  src/components/OAICoverage/index.tsx
Labels: type: feature request

#117 feat: cortex built in models
  package.json
  src/components/CopyCommand/index.tsx
  src/components/Select/index.tsx
  src/containers/Homepage/HeroSection/index.tsx
  src/hooks/useClipboard.ts
  src/pages/models.tsx
  tailwind.config.ts
  yarn.lock
Labels: type: feature request

#124 fix: cortex logo mark
  src/containers/Homepage/OAIReplacement/index.tsx
  static/img/logos/cortex-logo-mark.svg
Labels: type: bug

#126 chore: change owner name to author
  static/huggingface/hub.json
Labels: type: chore

#129 fix: missing list model
  docusaurus.config.ts
  src/components/OAICoverage/index.tsx
  src/pages/models.tsx
  src/utils/index.ts
Labels: type: bug

#131 chore: update logo url
  static/huggingface/hub.json
Labels: type: chore

#133 chore: update logo homebrew
  src/theme/Footer/index.tsx
  static/img/logos/homebrew-dark.svg
  static/img/logos/homebrew-white.svg
  static/img/logos/homebrew.svg
Labels: type: chore

#134 enhance: update model section cortex website
  src/containers/Homepage/OAIReplacement/index.tsx
Labels: type: enhancement

#139 fix: update model section
  src/containers/Homepage/OAIReplacement/index.tsx
Labels: type: bug, type: enhancement

#143 fix: update title and description
  src/containers/Homepage/HeroSection/index.tsx
Labels: type: bug, type: enhancement

#146 chore: update description hero section
  src/containers/Homepage/HeroSection/index.tsx
Labels: type: chore

#148 chore: correct model url with quant
  static/huggingface/hub.json
Labels: type: chore

#150 chore: Update hub.json
  static/huggingface/hub.json
Labels: type: chore

#153 chore: update description hero
  src/containers/Homepage/HeroSection/index.tsx
Labels: type: chore

#158 fix: social media link
  docusaurus.config.ts
Labels: type: bug
