Repository janhq/cortex.so, pull requests merged in 2024-10, with the labels that each got.

#203 chore: remove OpenAI compatible, changelog to left
  docusaurus.config.ts
  src/containers/Homepage/HeroSection/index.tsx
  src/containers/Homepage/SimpleHeroSection/index.tsx
Labels: type: chore

#204 chore: copy on OpenAI API equivalence
  docs/cortex-cpp.md
  docs/cortex-platform/about.mdx
  docs/embeddings.mdx
  docs/using-models.mdx
  docusaurus.config.ts
  static/openapi/jan.json
Labels: type: chore

#206 chore: update CLI
  docs/cli/chat.mdx
  docs/cli/engines/get.mdx
  docs/cli/engines/index.mdx
  docs/cli/engines/init.mdx
  docs/cli/engines/list.mdx
  docs/cli/models/index.mdx
  docs/cli/models/list.md
  docs/cli/ps.mdx
  docs/cli/run.mdx
  docs/cli/start.mdx
Labels: type: chore

#208 fix: change server default port
  docs/basic-usage/command-line.md
  docs/basic-usage/cortexrc.mdx
  docs/basic-usage/server.mdx
  docs/chat-completions.mdx
  docs/embeddings.mdx
  docs/quickstart.mdx
  docs/troubleshooting.mdx
  docs/using-models.mdx
Labels: type: bug

#209 feat: add download button
  src/components/Announcement/index.tsx
  src/components/DropdownDownload/index.tsx
  src/containers/Homepage/SimpleHeroSection/index.tsx
Labels: type: feature request

#210 fix: update link download
  src/components/DropdownDownload/index.tsx
Labels: type: bug

#212 fix: render mobile
  src/components/DropdownDownload/index.tsx
Labels: type: bug
